services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    environment:
      - ALLOW_RESET=true
    ports:
      - "8001:8000"   # map to avoid conflict with backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    volumes:
      - ./.streamlit/secrets.toml:/app/.streamlit/secrets.toml:ro
    depends_on:
      - chroma
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_EMBED_MODEL=text-embedding-3-small
      - OPENAI_CHAT_MODEL=gpt-4o-mini
      - OPENAI_MODERATION_MODEL=omni-moderation-latest
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - CHROMA_COLLECTION=${CHROMA_COLLECTION}
      - DATABASE_URL=${DB_URL}
      - SECRET_KEY=${SECRET_KEY}
      - API_KEY=${API_KEY}
    ports:
      - "8000:8000"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    volumes:
      - ./.streamlit/secrets.toml:/app/.streamlit/secrets.toml:ro
    depends_on:
      - backend
    environment:
      - STREAMLIT_SERVER_ENABLECORS=false
      - API_BASE=${API_BASE}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8501:8501"

networks:
  default:
    name: chroma-network
